#ChipScope Core Inserter Project File Version 3.0
#Sun Nov 23 14:56:26 PST 2014
Project.device.designInputFile=C\:\\Users\\inevitable_disaster\\Desktop\\senior_proj\\SeniorProject\\sys\\System_cs.ngc
Project.device.designOutputFile=C\:\\Users\\inevitable_disaster\\Desktop\\senior_proj\\SeniorProject\\sys\\System_cs.ngc
Project.device.deviceFamily=13
Project.device.enableRPMs=true
Project.device.outputDirectory=C\:\\Users\\inevitable_disaster\\Desktop\\senior_proj\\SeniorProject\\sys\\_ngo
Project.device.useSRL16=true
Project.filter.dimension=4
Project.filter<0>=
Project.filter<1>=cpu/
Project.filter<2>=cpu
Project.filter<3>=clk
Project.icon.boundaryScanChain=1
Project.icon.enableExtTriggerIn=false
Project.icon.enableExtTriggerOut=false
Project.icon.triggerInPinName=
Project.icon.triggerOutPinName=
Project.unit.dimension=1
Project.unit<0>.clockChannel=clk25MHz
Project.unit<0>.clockEdge=Rising
Project.unit<0>.dataChannel<0>=bus_req<2>
Project.unit<0>.dataChannel<10>=bus_data<5>
Project.unit<0>.dataChannel<11>=bus_data<6>
Project.unit<0>.dataChannel<12>=bus_data<7>
Project.unit<0>.dataChannel<13>=bus_data<8>
Project.unit<0>.dataChannel<14>=bus_data<9>
Project.unit<0>.dataChannel<15>=bus_data<10>
Project.unit<0>.dataChannel<16>=bus_data<11>
Project.unit<0>.dataChannel<17>=bus_data<12>
Project.unit<0>.dataChannel<18>=bus_data<13>
Project.unit<0>.dataChannel<19>=bus_data<14>
Project.unit<0>.dataChannel<1>=bus_req<7>
Project.unit<0>.dataChannel<20>=bus_data<15>
Project.unit<0>.dataChannel<21>=bus_ack<0>
Project.unit<0>.dataChannel<22>=bus_ack<2>
Project.unit<0>.dataChannel<23>=bus_ack<3>
Project.unit<0>.dataChannel<24>=bus_ack<4>
Project.unit<0>.dataChannel<25>=bus_ack<6>
Project.unit<0>.dataChannel<26>=bus_ack<7>
Project.unit<0>.dataChannel<2>=AudioCopper audio_out<0>
Project.unit<0>.dataChannel<3>=AudioCopper m_addr_we
Project.unit<0>.dataChannel<4>=AudioCopper ch0_nr_we
Project.unit<0>.dataChannel<5>=bus_data<0>
Project.unit<0>.dataChannel<6>=bus_data<1>
Project.unit<0>.dataChannel<7>=bus_data<2>
Project.unit<0>.dataChannel<8>=bus_data<3>
Project.unit<0>.dataChannel<9>=bus_data<4>
Project.unit<0>.dataDepth=4096
Project.unit<0>.dataEqualsTrigger=true
Project.unit<0>.dataPortWidth=27
Project.unit<0>.enableGaps=false
Project.unit<0>.enableStorageQualification=true
Project.unit<0>.enableTimestamps=false
Project.unit<0>.timestampDepth=0
Project.unit<0>.timestampWidth=0
Project.unit<0>.triggerChannel<0><0>=bus_req<2>
Project.unit<0>.triggerChannel<0><1>=bus_req<7>
Project.unit<0>.triggerChannel<0><2>=AudioCopper audio_out<0>
Project.unit<0>.triggerChannel<0><3>=AudioCopper m_addr_we
Project.unit<0>.triggerChannel<0><4>=AudioCopper ch0_nr_we
Project.unit<0>.triggerChannel<0><5>=AudioCopper ch1_nr_we
Project.unit<0>.triggerChannel<0><6>=AudioCopper ch2_nr_we
Project.unit<0>.triggerChannel<0><7>=AudioCopper ch3_nr_we
Project.unit<0>.triggerChannel<1><0>=bus_data<0>
Project.unit<0>.triggerChannel<1><10>=bus_data<10>
Project.unit<0>.triggerChannel<1><11>=bus_data<11>
Project.unit<0>.triggerChannel<1><12>=bus_data<12>
Project.unit<0>.triggerChannel<1><13>=bus_data<13>
Project.unit<0>.triggerChannel<1><14>=bus_data<14>
Project.unit<0>.triggerChannel<1><15>=bus_data<15>
Project.unit<0>.triggerChannel<1><1>=bus_data<1>
Project.unit<0>.triggerChannel<1><2>=bus_data<2>
Project.unit<0>.triggerChannel<1><3>=bus_data<3>
Project.unit<0>.triggerChannel<1><4>=bus_data<4>
Project.unit<0>.triggerChannel<1><5>=bus_data<5>
Project.unit<0>.triggerChannel<1><6>=bus_data<6>
Project.unit<0>.triggerChannel<1><7>=bus_data<7>
Project.unit<0>.triggerChannel<1><8>=bus_data<8>
Project.unit<0>.triggerChannel<1><9>=bus_data<9>
Project.unit<0>.triggerChannel<2><0>=bus_ack<0>
Project.unit<0>.triggerChannel<2><1>=bus_ack<2>
Project.unit<0>.triggerChannel<2><2>=bus_ack<3>
Project.unit<0>.triggerChannel<2><3>=bus_ack<4>
Project.unit<0>.triggerChannel<2><4>=bus_ack<6>
Project.unit<0>.triggerChannel<2><5>=bus_ack<7>
Project.unit<0>.triggerConditionCountWidth=0
Project.unit<0>.triggerMatchCount<0>=1
Project.unit<0>.triggerMatchCount<1>=1
Project.unit<0>.triggerMatchCount<2>=1
Project.unit<0>.triggerMatchCountWidth<0><0>=0
Project.unit<0>.triggerMatchCountWidth<1><0>=0
Project.unit<0>.triggerMatchCountWidth<2><0>=0
Project.unit<0>.triggerMatchType<0><0>=1
Project.unit<0>.triggerMatchType<1><0>=1
Project.unit<0>.triggerMatchType<2><0>=1
Project.unit<0>.triggerPortCount=3
Project.unit<0>.triggerPortIsData<0>=true
Project.unit<0>.triggerPortIsData<1>=true
Project.unit<0>.triggerPortIsData<2>=true
Project.unit<0>.triggerPortWidth<0>=8
Project.unit<0>.triggerPortWidth<1>=16
Project.unit<0>.triggerPortWidth<2>=6
Project.unit<0>.triggerSequencerLevels=16
Project.unit<0>.triggerSequencerType=1
Project.unit<0>.type=ilapro
