#ChipScope Core Inserter Project File Version 3.0
#Sat Nov 29 15:59:33 PST 2014
Project.device.designInputFile=C\:\\Users\\inevitable_disaster\\Desktop\\senior_proj\\SeniorProject\\sys\\System_cs.ngc
Project.device.designOutputFile=C\:\\Users\\inevitable_disaster\\Desktop\\senior_proj\\SeniorProject\\sys\\System_cs.ngc
Project.device.deviceFamily=13
Project.device.enableRPMs=true
Project.device.outputDirectory=C\:\\Users\\inevitable_disaster\\Desktop\\senior_proj\\SeniorProject\\sys\\_ngo
Project.device.useSRL16=true
Project.filter.dimension=4
Project.filter<0>=
Project.filter<1>=cpu/
Project.filter<2>=cpu
Project.filter<3>=clk
Project.icon.boundaryScanChain=1
Project.icon.enableExtTriggerIn=false
Project.icon.enableExtTriggerOut=false
Project.icon.triggerInPinName=
Project.icon.triggerOutPinName=
Project.unit.dimension=1
Project.unit<0>.clockChannel=clk25MHz
Project.unit<0>.clockEdge=Rising
Project.unit<0>.dataChannel<0>=bus_req<2>
Project.unit<0>.dataChannel<1>=bus_req<6>
Project.unit<0>.dataChannel<2>=bus_req<7>
Project.unit<0>.dataChannel<3>=bus_master_ack<2>
Project.unit<0>.dataChannel<4>=bus_master_ack<6>
Project.unit<0>.dataChannel<5>=bus_master_ack<7>
Project.unit<0>.dataChannel<6>=vga_ctrl buffer1 write_address<0>
Project.unit<0>.dataChannel<7>=vga_ctrl buffer1 write_address<1>
Project.unit<0>.dataDepth=2048
Project.unit<0>.dataEqualsTrigger=true
Project.unit<0>.dataPortWidth=30
Project.unit<0>.enableGaps=false
Project.unit<0>.enableStorageQualification=true
Project.unit<0>.enableTimestamps=false
Project.unit<0>.timestampDepth=0
Project.unit<0>.timestampWidth=0
Project.unit<0>.triggerChannel<0><0>=bus_req<2>
Project.unit<0>.triggerChannel<0><1>=bus_req<6>
Project.unit<0>.triggerChannel<0><2>=bus_req<7>
Project.unit<0>.triggerChannel<0><3>=bus_master_ack<2>
Project.unit<0>.triggerChannel<0><4>=bus_master_ack<6>
Project.unit<0>.triggerChannel<0><5>=bus_master_ack<7>
Project.unit<0>.triggerChannel<0><6>=vga_ctrl buffer1 write_address<0>
Project.unit<0>.triggerChannel<0><7>=vga_ctrl buffer1 write_address<1>
Project.unit<0>.triggerChannel<1><0>=bus_data<0>
Project.unit<0>.triggerChannel<1><10>=bus_data<10>
Project.unit<0>.triggerChannel<1><11>=bus_data<11>
Project.unit<0>.triggerChannel<1><12>=bus_data<12>
Project.unit<0>.triggerChannel<1><13>=bus_data<13>
Project.unit<0>.triggerChannel<1><14>=bus_data<14>
Project.unit<0>.triggerChannel<1><15>=bus_data<15>
Project.unit<0>.triggerChannel<1><1>=bus_data<1>
Project.unit<0>.triggerChannel<1><2>=bus_data<2>
Project.unit<0>.triggerChannel<1><3>=bus_data<3>
Project.unit<0>.triggerChannel<1><4>=bus_data<4>
Project.unit<0>.triggerChannel<1><5>=bus_data<5>
Project.unit<0>.triggerChannel<1><6>=bus_data<6>
Project.unit<0>.triggerChannel<1><7>=bus_data<7>
Project.unit<0>.triggerChannel<1><8>=bus_data<8>
Project.unit<0>.triggerChannel<1><9>=bus_data<9>
Project.unit<0>.triggerChannel<2><0>=bus_ctrller currentState<0>
Project.unit<0>.triggerChannel<2><1>=bus_ctrller currentState<1>
Project.unit<0>.triggerChannel<2><2>=bus_ctrller currentState<2>
Project.unit<0>.triggerChannel<2><3>=bus_ctrller slave_en<2>
Project.unit<0>.triggerChannel<2><4>=bus_ctrller slave_en<4>
Project.unit<0>.triggerChannel<2><5>=bus_ctrller slave_en<7>
Project.unit<0>.triggerChannel<3><0>=vga_ctrl bus_if buf_write_addr<0>
Project.unit<0>.triggerChannel<3><1>=vga_ctrl bus_if buf_write_addr<1>
Project.unit<0>.triggerChannel<3><2>=vga_ctrl bus_if buf_write_addr<2>
Project.unit<0>.triggerChannel<4><0>=sram_ctrl burst_counter<0>
Project.unit<0>.triggerChannel<4><1>=sram_ctrl burst_counter<1>
Project.unit<0>.triggerChannel<4><2>=sram_ctrl burst_counter<2>
Project.unit<0>.triggerChannel<4><3>=sram_ctrl burst_counter<3>
Project.unit<0>.triggerChannel<5><0>=sram_ctrl currentState<0>
Project.unit<0>.triggerChannel<5><1>=sram_ctrl currentState<1>
Project.unit<0>.triggerChannel<5><2>=sram_ctrl currentState<2>
Project.unit<0>.triggerChannel<5><3>=sram_ctrl currentState<3>
Project.unit<0>.triggerChannel<6><0>=sram_ctrl maddr<0>
Project.unit<0>.triggerChannel<6><10>=sram_ctrl maddr<10>
Project.unit<0>.triggerChannel<6><11>=sram_ctrl maddr<11>
Project.unit<0>.triggerChannel<6><12>=sram_ctrl maddr<12>
Project.unit<0>.triggerChannel<6><13>=sram_ctrl maddr<13>
Project.unit<0>.triggerChannel<6><14>=sram_ctrl maddr<14>
Project.unit<0>.triggerChannel<6><15>=sram_ctrl maddr<15>
Project.unit<0>.triggerChannel<6><16>=sram_ctrl maddr<16>
Project.unit<0>.triggerChannel<6><17>=sram_ctrl maddr<17>
Project.unit<0>.triggerChannel<6><18>=sram_ctrl maddr<18>
Project.unit<0>.triggerChannel<6><19>=sram_ctrl maddr<19>
Project.unit<0>.triggerChannel<6><1>=sram_ctrl maddr<1>
Project.unit<0>.triggerChannel<6><20>=sram_ctrl maddr<20>
Project.unit<0>.triggerChannel<6><21>=sram_ctrl maddr<21>
Project.unit<0>.triggerChannel<6><22>=sram_ctrl maddr<22>
Project.unit<0>.triggerChannel<6><2>=sram_ctrl maddr<2>
Project.unit<0>.triggerChannel<6><3>=sram_ctrl maddr<3>
Project.unit<0>.triggerChannel<6><4>=sram_ctrl maddr<4>
Project.unit<0>.triggerChannel<6><5>=sram_ctrl maddr<5>
Project.unit<0>.triggerChannel<6><6>=sram_ctrl maddr<6>
Project.unit<0>.triggerChannel<6><7>=sram_ctrl maddr<7>
Project.unit<0>.triggerChannel<6><8>=sram_ctrl maddr<8>
Project.unit<0>.triggerChannel<6><9>=sram_ctrl maddr<9>
Project.unit<0>.triggerChannel<7><0>=vga_ctrl pixel<0>
Project.unit<0>.triggerChannel<7><1>=vga_ctrl pixel<1>
Project.unit<0>.triggerChannel<7><2>=vga_ctrl pixel<2>
Project.unit<0>.triggerChannel<7><3>=vga_ctrl pixel<3>
Project.unit<0>.triggerChannel<7><4>=vga_ctrl pixel<4>
Project.unit<0>.triggerChannel<7><5>=vga_ctrl pixel<5>
Project.unit<0>.triggerChannel<7><6>=vga_ctrl pixel<6>
Project.unit<0>.triggerChannel<7><7>=vga_ctrl pixel<7>
Project.unit<0>.triggerChannel<8><0>=vga_ctrl buffer0 read_address<0>
Project.unit<0>.triggerChannel<8><1>=vga_ctrl buffer0 read_address<1>
Project.unit<0>.triggerChannel<8><2>=vga_ctrl buffer0 read_address<2>
Project.unit<0>.triggerChannel<8><3>=vga_ctrl buffer0 we
Project.unit<0>.triggerChannel<8><4>=vga_ctrl buffer0 write_address<0>
Project.unit<0>.triggerChannel<8><5>=vga_ctrl buffer0 write_address<1>
Project.unit<0>.triggerChannel<8><6>=vga_ctrl buffer0 write_address<2>
Project.unit<0>.triggerConditionCountWidth=0
Project.unit<0>.triggerMatchCount<0>=1
Project.unit<0>.triggerMatchCount<1>=1
Project.unit<0>.triggerMatchCount<2>=1
Project.unit<0>.triggerMatchCount<3>=1
Project.unit<0>.triggerMatchCount<4>=1
Project.unit<0>.triggerMatchCount<5>=1
Project.unit<0>.triggerMatchCount<6>=1
Project.unit<0>.triggerMatchCount<7>=1
Project.unit<0>.triggerMatchCount<8>=1
Project.unit<0>.triggerMatchCountWidth<0><0>=0
Project.unit<0>.triggerMatchCountWidth<1><0>=0
Project.unit<0>.triggerMatchCountWidth<2><0>=0
Project.unit<0>.triggerMatchCountWidth<3><0>=0
Project.unit<0>.triggerMatchCountWidth<4><0>=0
Project.unit<0>.triggerMatchCountWidth<5><0>=0
Project.unit<0>.triggerMatchCountWidth<6><0>=0
Project.unit<0>.triggerMatchCountWidth<7><0>=0
Project.unit<0>.triggerMatchCountWidth<8><0>=0
Project.unit<0>.triggerMatchType<0><0>=1
Project.unit<0>.triggerMatchType<1><0>=1
Project.unit<0>.triggerMatchType<2><0>=1
Project.unit<0>.triggerMatchType<3><0>=1
Project.unit<0>.triggerMatchType<4><0>=1
Project.unit<0>.triggerMatchType<5><0>=1
Project.unit<0>.triggerMatchType<6><0>=1
Project.unit<0>.triggerMatchType<7><0>=1
Project.unit<0>.triggerMatchType<8><0>=1
Project.unit<0>.triggerPortCount=9
Project.unit<0>.triggerPortIsData<0>=true
Project.unit<0>.triggerPortIsData<10>=false
Project.unit<0>.triggerPortIsData<11>=false
Project.unit<0>.triggerPortIsData<12>=false
Project.unit<0>.triggerPortIsData<13>=false
Project.unit<0>.triggerPortIsData<14>=false
Project.unit<0>.triggerPortIsData<15>=false
Project.unit<0>.triggerPortIsData<1>=true
Project.unit<0>.triggerPortIsData<2>=true
Project.unit<0>.triggerPortIsData<3>=true
Project.unit<0>.triggerPortIsData<4>=true
Project.unit<0>.triggerPortIsData<5>=true
Project.unit<0>.triggerPortIsData<6>=true
Project.unit<0>.triggerPortIsData<7>=true
Project.unit<0>.triggerPortIsData<8>=true
Project.unit<0>.triggerPortIsData<9>=false
Project.unit<0>.triggerPortWidth<0>=8
Project.unit<0>.triggerPortWidth<1>=16
Project.unit<0>.triggerPortWidth<2>=6
Project.unit<0>.triggerPortWidth<3>=3
Project.unit<0>.triggerPortWidth<4>=4
Project.unit<0>.triggerPortWidth<5>=4
Project.unit<0>.triggerPortWidth<6>=23
Project.unit<0>.triggerPortWidth<7>=8
Project.unit<0>.triggerPortWidth<8>=7
Project.unit<0>.triggerSequencerLevels=16
Project.unit<0>.triggerSequencerType=1
Project.unit<0>.type=ilapro
